### ISSUE TITLE
[BUG] Messages are ignored with "Message not exist in record" exception

### ISSUE THREAD

**Issue by artem-garmash** [streamnative/pulsar-io-cloud-storage#7] opened 2020-11-03 14:04 UTC
**Describe the bug**
I'm following the instruction to test the connector from README.md but all messages are being ignored with "Message not exist in record"  exception and nothing is saved to S3.

**To Reproduce**
https://github.com/streamnative/pulsar-io-cloud-storage#usage
The only difference is own class instead of TestRecord.
```
public class Event {
    public String user_id;
    public String os;

    public Event(String user_id, String os) {
        this.user_id = user_id;
        this.os = os;
    }

    public Event() {
    }
}
```

**Expected behavior**
Messages are saved to S3

**Additional context**
Sink status:
```
{
  "numInstances" : 1,
  "numRunning" : 1,
  "instances" : [ {
    "instanceId" : 0,
    "status" : {
      "running" : true,
      "error" : "",
      "numRestarts" : 0,
      "numReadFromPulsar" : 2,
      "numSystemExceptions" : 0,
      "latestSystemExceptions" : [ ],
      "numSinkExceptions" : 0,
      "latestSinkExceptions" : [ {
        "exceptionString" : "Message not exist in record",
        "timestampMs" : 1604410860088
      }, {
        "exceptionString" : "Message not exist in record",
        "timestampMs" : 1604410860095
      } ],
      "numWrittenToSink" : 0,
      "lastReceivedTime" : 1604410860093,
      "workerId" : "c-standalone-fw-localhost-8080"
    }
  } ]
}
```

Topic schema:
```
{
  "version": 2,
  "schemaInfo": {
    "name": "my-topic-2-avro",
    "schema": {
      "type": "record",
      "name": "Event",
      "fields": [
        {
          "name": "user_id",
          "type": [
            "null",
            "string"
          ]
        },
        {
          "name": "os",
          "type": [
            "null",
            "string"
          ]
        }
      ]
    },
    "type": "AVRO",
    "properties": {
      "__alwaysAllowNull": "true",
      "__jsr310ConversionEnabled": "false"
    }
  }
}
```

Same topics works with postgresql sing or cli consumer.  Tried with JSON and AVRO schemas.

**Comment by sijie** [comment] 2020-12-09 00:20
@artem-garmash thank you for reporting this. Sorry for the late reply! We will take a look at this issue.

**Comment by jianyun8023** [comment] 2021-03-08 07:52
The error is because we can't get the Message instance, because the Source in Function is not a topic message, but postgresql, and cloud-storage expects to get the PulsarRecord message.

During the run, if I use only Record data and not PulsarRecord data, I will not be able to process Schema. So I need to use Pulsar topic as source.

**Comment by jianyun8023** [comment] 2021-03-11 10:23
pulsar-io-cloud-storage needs to use a schema to hold structural information about the data, so it can only use the Pulsar topic as message input. You need to write your records to the topic and then use pulsar-io-cloud-storage to write them out.

**Comment by artem-garmash** [comment] 2021-03-12 15:21
@jianyun8023, thanks for the reply. My pulsar topic had schema definition as you can see in the bug description. I literally followed README instructions 1:1 to test pulsar-io-cloud-storage but it didn't work.
At the end of my attempts I tried to use jdbc connector with postgres sink instead of pulsar-io-cloud-storage just to verify that my topic/setup worked. And it all worked with jdbc connector, consuming the same pulsar topic.

**Comment by freeznet** [comment] 2022-02-15 01:57
I cannot reproduce this issue with the latest version, so I assume this issue has been resolved in past commits. Feel free to re-open it if there is any more context.

**Closed by freeznet** 2022-02-15 01:57 UTC
Labels: type/bug, platform/serverless
