### ISSUE TITLE
[BUG] Verify the connector can interact with gcs and azure blob store correctly

### ISSUE THREAD

**Issue by nlu90** [streamnative/pulsar-io-cloud-storage#45] opened 2021-06-09 06:44 UTC
**Describe the bug**
Currently the connector lack verification of running with
- [ ] gcs
- [ ] azure blob store

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by alpreu** [comment] 2022-10-12 12:15
Closing this because it is confirmed to be working now

**Closed by alpreu** 2022-10-12 12:15 UTC
Labels: type/bug

**Comment by freeznet** [comment] 2022-10-13 01:10
@alpreu the gcs is working, but havnt done any implementation and tests with Azure yet.

**Comment by alpreu** [comment] 2022-10-13 11:40
> @alpreu the gcs is working, but havnt done any implementation and tests with Azure yet.

I have opened a follow-up ticket for Azure here #467
